Add metadata kind email and new control for Audit
getodk/build pull request #284
Opened 2022-01-31 05:30 UTC by florianm

This PR brings the two final new features of frankenPR #266. (close #266)

In a small addition, the last missing metadata kind "email" is added in two places:
* 1/2: email is added to the list of available metadata kinds,
* 2/2: email is added to the XML in the same way as e.g. username.

The main part of the PR is to support audit, which is different to the other metadata fields as it has its own [four attributes](https://getodk.github.io/xforms-spec/#audit-attributes), but always has the label "Audit" (so that can be made implicit).
Audit is added as a top level control element. Much of the handling is similar to metadata (there, some `if` clauses get extended to include the control type `audit`), some is different enough to warrant its own code block. I'll annotate the code changes with what the sections do.

## Walkthrough
Let's build a simple form to show the new behaviour of email and audit.
One text field:
![image](https://user-images.githubusercontent.com/762815/151741508-f460b9eb-1dc3-4c3b-870a-cc92953cfc1e.png)

The required namespace `orx` was already added in #281.
We now see the meta node being prefixed as `orx:meta` as per the [XForms metadata spec](https://getodk.github.io/xforms-spec/#metadata).

```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:orx="http://openrosa.org/xforms" xmlns:odk="http://www.opendatakit.org/xforms">
  <h:head>
    <h:title>164 Audit Email</h:title>
    <model>
      <instance>
        <data id="164-Audit-Email" orx:version="1643605416">
          <orx:meta>
            <orx:instanceID/>
          </orx:meta>
          <text1/>
        </data>
      </instance>
      <itext>
        <translation lang="English">
          <text id="/data/text1:label">
            <value>Text 1 label</value>
          </text>
          <text id="/data/text1:hint">
            <value>Text 1 hint</value>
          </text>
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" jr:preload="uid"/>
      <bind nodeset="/data/text1" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/text1">
      <label ref="jr:itext('/data/text1:label')"/>
      <hint ref="jr:itext('/data/text1:hint')"/>
    </input>
  </h:body>
</h:html>
```

Adding existing metadata `username` and new metadata `email`, we see that email behaves exactly like username:
![image](https://user-images.githubusercontent.com/762815/151741950-3b33cb48-ae32-477f-b5cf-27e7659724a1.png)

```
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" jr:preload="uid"/>
      <bind nodeset="/data/text1" type="string"/>
      <bind nodeset="/data/username" type="string" jr:preload="property" jr:preloadParams="username"/>
      <bind nodeset="/data/email" type="string" jr:preload="property" jr:preloadParams="email"/>
```

Adding a new control "Audit" shows the audit attributes as first level properties, populated with defaults, and the control being labelled as "Audit". The data name also defaults to "audit" but can be adjusted.
![image](https://user-images.githubusercontent.com/762815/151742090-18628a12-f509-4a7e-8ead-7dbd05fc6138.png)
The XML output now reads:
```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:orx="http://openrosa.org/xforms" xmlns:odk="http://www.opendatakit.org/xforms">
  <h:head>
    <h:title>164 Audit Email</h:title>
    <model>
      <instance>
        <data id="164-Audit-Email" orx:version="1643605882">
          <orx:meta>
            <orx:instanceID/>
            <orx:audit/>
          </orx:meta>
          <text1/>
          <username/>
          <email/>
        </data>
      </instance>
      <itext>
        <translation lang="English">
          <text id="/data/text1:label">
            <value>Text 1 label</value>
          </text>
          <text id="/data/text1:hint">
            <value>Text 1 hint</value>
          </text>
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" jr:preload="uid"/>
      <bind nodeset="/data/text1" type="string"/>
      <bind nodeset="/data/username" type="string" jr:preload="property" jr:preloadParams="username"/>
      <bind nodeset="/data/email" type="string" jr:preload="property" jr:preloadParams="email"/>
      <bind nodeset="/data/meta/audit" type="binary" odk:location-priority="balanced" odk:location-min-interval="20" odk:location-max-age="60" odk:track-changes="true"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/text1">
      <label ref="jr:itext('/data/text1:label')"/>
      <hint ref="jr:itext('/data/text1:hint')"/>
    </input>
  </h:body>
</h:html>
```

Changing the audit parameter `location priority` to "off" creates the bind node 
```
<bind nodeset="/data/meta/audit" type="binary" odk:track-changes="true"/>
```

Changing the audit parameter `track changes` to "false" creates the bind node
```
      <bind nodeset="/data/meta/audit" type="binary" odk:track-changes="false"/>
```
which obviously makes sense only if combined with location tracking enabled (prio other than "off"), e.g.
```
      <bind nodeset="/data/meta/audit" type="binary" odk:location-priority="high-accuracy" odk:location-min-interval="20" odk:location-max-age="60" odk:track-changes="false"/>
```

## Form and submissions
[164-Audit-Email.zip](https://github.com/getodk/build/files/7968320/164-Audit-Email.zip)
The attached ZIP is the export of two test submissions to the (also included) XForm. I've edited out my (verified correct) coordinates Ith `xxx` where recorded by the audit log. I can also see my email which I've set in the Collect metadata as "noreply@email.org" - looks like a default, but that was actually me. The top level audit log contains the audit for both submissions, the media/audit.csv contains only the last form's audit log.

From these test submissions I conclude that the email and audit controls work and generate a valid XForm. I didn't test any edge cases or other forms yet.

2022-01-31 05:36 UTC, florianm commented on public/javascripts/control.js
> +        }
Audit controls get a fixed label "Audit". Users can choose a separate data name (default: "audit" instead of "untitled").

2022-01-31 05:36 UTC, florianm commented on public/javascripts/control.js
> +            else if ((type == 'group') || (type == 'branch') || (type == 'metadata') || (type == 'audit'))
Like metadata, audit does not get default control properties (label, help etc).

2022-01-31 05:37 UTC, florianm commented on public/javascripts/control.js
> +                        options: [ 'Device ID', 'Start Time', 'End Time', 'Today', 'Username', 'Email', 'Subscriber ID', 'SIM Serial', 'Phone Number', 'Start Geopoint' ],
Email 1/2: add email as available metadata kind.

2022-01-31 05:38 UTC, florianm commented on public/javascripts/control.js
> +          },
Audit gets a custom set of control properties: no `kind` (as there's only one choice, "audit"), plus the four metadata attributes.

2022-01-31 05:38 UTC, florianm commented on public/javascripts/control.js
> +            description: 'Audit metadata can track form changes and/or device location.',
Context help for audit control.

2022-01-31 05:40 UTC, florianm commented on public/javascripts/data.js
> +        if ((control.type == 'group') || (control.type == 'branch') || (control.type == 'metadata') || (control.type == 'audit'))
No default properties for audit, like metadata.

2022-01-31 05:42 UTC, florianm commented on public/javascripts/data.js
>              property.value = control[key];
Like metadata, audit captures no user-entered value.

2022-01-31 05:44 UTC, florianm commented on public/javascripts/data.js
> +        }
This pushes two elements into the exported XML, meta and bind node. See inline comments.

2022-01-31 05:45 UTC, florianm commented on public/javascripts/data.js
> +            }
Email 2/2: push the bind node into the exported XML.

2022-01-31 05:47 UTC, florianm commented on server/views/index.erb
> +          <li><a class="toolButton audit" rel="audit">Audit</a></li>
Footer menu: add new control type "Audit". No changes to `styles.css` needed, the class `toolButton` applies the correct style.

2022-02-02 18:11 UTC, lognaturel commented
> meta node being prefixed as orx:meta

Note that Enketo doesn't currently support editing records that have a namespaced meta block: https://github.com/enketo/enketo-core/issues/835. This update will be available in Central v1.14 (~2 weeks from now). I think this can move forward anyway but wanted to capture this info.

2022-02-02 18:37 UTC, florianm commented
> > meta node being prefixed as orx:meta
> 
> Note that Enketo doesn't currently support editing records that have a namespaced meta block: [enketo/enketo-core#835](https://github.com/enketo/enketo-core/issues/835). This update will be available in Central v1.14 (~2 weeks from now). I think this can move forward anyway but wanted to capture this info.

Good to know! I just followed the XForms spec here. Seeing the Enketo fix is rolled out by the time we've got Build and build2xlsform PRs merged and deployed, do I understand you correctly to keep the `orx` prefixes?

2022-02-02 20:37 UTC, lognaturel commented
> The data name also defaults to "audit" but can be adjusted.

The audit is only populated if there's a node named `audit` in the model so this can't be configurable.

2022-02-02 20:38 UTC, lognaturel commented
> Seeing the Enketo fix is rolled out by the time we've got Build and build2xlsform PRs merged and deployed, do I understand you correctly to keep the orx prefixes?

Yes, that's what I think we should do. The issue won't affect data capture as far as I know, only edits. And there will be a solution -- upgrade Enketo/Central.

2022-02-02 20:47 UTC, lognaturel requested changes
I agree with the choices you've made on the UI/flow side. I think that to make this safer we should forget about namespacing meta and audit. You'll also need to make sure that the node name is fixed.

2022-02-02 23:08 UTC, florianm commented
That makes sense and I'll send the changes.

Since the data name is now fixed too and we'll never want two audit fields, and the position in the form definition does not impact how audit gets represented in the XML, I'm wondering whether it wouldn't be best configured in the form settings near autosend/delete settings.

What is your preference, @lognaturel?

2022-02-07 04:04 UTC, florianm commented
I suggest closing this PR in favour of #287 and #286.

2022-02-07 04:04 UTC, closed without merging